elastic/go-docappender

appender.go, appender_test.go
Updates the appender to record the number of requests that failed due to a client error (4xx), or a server error (5xx). Introduces two new fields `Stats.FailedClient` and `Stats.FailedServer`.
=> appender: Add FailedClient and FailedServer stats

appender.go, appender_test.go
For `TooMany`, `FailedClient` and `FailedServer` to equal `Failed`.
=> stats: Exclude TooMany from FailedClient

appender.go, appender_test.go
Include the index name in the indexing failure, making it easier to tell which index may be returning indexing failures.
=> appender: include index name in index failure

bulk_indexer.go
Fix https://github.com/elastic/go-docappender/pull/33#pullrequestreview-1489540847
I updated the code locally but didn't push the changes :sweat: 
Sorry @axw
=> perf: use a minimal bulk response struct to decode body

appender.go, appender_test.go
The `flush` transaction is quite obscure. We could be flushing many things.
So this renamed it to `docappender.flush`, which should be more meaningful.
While I was there, I also removed the global variable, and added error reporting for failed documents.
=> Rename transaction, and remove global variable

appender.go, bulk_indexer.go, go.mod, go.sum
We're not using the map keys and just iterating on the values so
there is no need for a nested struct.
We can just flatten the maps and use a slice.
Replace go-json with gjson and store the item responses in a slice.
The slice was already being reused so there is no additional
allocations.
This significantly reduce memory usage and allocations.
```
│  before.txt  │     after-nojson-perf-final.txt     │
│    sec/op    │    sec/op     vs base               │
Appender/NoCompression-20               503.8n ±  6%   476.1n ±  9%  -5.49% (p=0.009 n=10)
Appender/NoCompressionScaling-20        874.7n ± 15%   848.9n ± 42%       ~ (p=0.305 n=10)
Appender/BestSpeed-20                   793.3n ±  4%   844.8n ±  5%  +6.49% (p=0.003 n=10)
Appender/BestSpeedScaling-20            789.6n ±  4%   775.7n ± …
```
=> perf: replace goccy with gjson and store response items in a slice 

appender.go, appender_test.go
Tags the `docappender.flush` transaction with the number of documents that are sent in the bulk request. The tag name is `documents`.
=> tracing: Add `documents` transaction tag

.github/workflows/ci.yml, appender.go, appender_test.go, config.go, go.mod, metric.go
closes #37 
Support otel metrics for the existing metrics so it can be exported by the client
=> feat: support otel metrics for existing metrics

appender.go, appender_test.go, metric.go
Instead of creating several metrics having status in names, create a single metric with different attributes/dimensions.
Before -> after
- `elasticsearch.events.processed` -> `elasticsearch.events.processed {status: "Success"}`
- `elasticsearch.failed.client.count ` ->  `elasticsearch.events.processed {status: "FailedClient"}`
- `elasticsearch.failed.server.count` -> `elasticsearch.events.processed {status: "FailedServer"}`
- `elasticsearch.failed.too_many_reqs` -> `elasticsearch.events.processed {status: "TooMany"}
`
The outcome of it is the same with the #53, but it uses synchronous instruments instead.
=> feat: dimensional metrics for `elasticsearch.events.processed` metric 

appender_bench_test.go, appender_test.go, bulk_indexer.go
Removes the field mapper exception field preview returned in the error reason by Elasticsearch.
Closes #80
=> bulk_indexer: Remove ES field mapper field preview

appender.go, appender_test.go, docappendertest/docappendertest.go
Count the documents sent in a bulk request that times out as processed but tagged with `status: "Timeout"`. This metric is only added to the non-legacy metrics.
=> Count documents from requests that time out

appender.go, bulk_indexer.go
Removes the `bulkIndexerItem.Action` field since it's set to a known value. Having all `bulkIndexerItem` with a field with the same value is unnecessary. It saves a few bytes of memory.
Benchmarks remain largely the same so that I won't expect a significant performance benefit, just more readable code and the removal of the redundant field.
```
benchstat main.txt main-action.txt                                                                                                                                                                       <region:us-east-1>
goos: darwin
goarch: arm64
pkg: github.com/elastic/go-docappender
│   main.txt    │           main-action.txt           │
│    sec/op     │    sec/op     vs base               │
Appender/NoCompression-12                1.044µ ± 43% …
```
=> bulk_indexer: Use "create" constant

.github/workflows/bench-diff.yml, .github/workflows/label-elastic-pull-requests.yml, .github/workflows/opentelemetry.yml
Enable the bench-diff report for PRs and branches.
Minor change to support wildcards for all the run GitHub workflows so they can be exported to traces using the OpenTelemetry.
https://github.com/elastic/apm-data/pull/170 is a similar one but in a different GitHub repository.
Run the go test command with the bench flag using https://github.com/WillAbides/benchdiff-action and report the results with a link to the output using a GitHub check.
For such, it uses the current PR and the `main` branch revisions to run a go test command for each revision and compare with.
https://github.com/WillAbides/benchdiff-action?tab=readme-ov-file#benchdiff_args explains how to configure the benchdiff.
See https://github.com/elastic/go-docappender/pull/113/checks?check_run_id=21203555733
Closes #112
=> github-action: enable bench diff and opentelemetry for all the GitHub workflows

.github/workflows/bench-diff.yml
`github.event_name != 'pull_request'` will be always true since it listens for `pull_request_target` events.
Let's use the startswith condition for `pull_request`.
=> github-action: support pull_request_target and pull_request events

.github/workflows/label-elastic-pull-requests.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
We want to set the default permissions for workflows to read-only for contents. 
This is a security measure to prevent accidental changes to the repository.
This change adds a top-level permissions block to all workflows in the .github/workflows directory.
```yaml
permissions:
contents: read
```
In some cases workflows might need more permissions than just `contents: read`.
Please checkout this branch and add the necessary permissions to the workflows.
If your workflow uses a Personal Access Token (PAT), we can still add the permissions block,
but it will not have any effect.
Merging this PR as is might cause workflows that need more permissions to fail.
If there are any questions, please reach out to …
=> security: add permissions block to workflows

bulk_indexer.go, go.mod, go.sum
Replaces the stdlib `compress/gzip` with `klauspost/compress/gzip`. It is slightly faster (by using less CPU) and results in the same allocs. That is assuming default gzip compression (6).
Using an extraneous application to benchmark the change, I was able to observe `10-11%` more throughput (measured in events per second) and lower CPU usage.
Using the same container with 2vCPU set and GOMAXPROCS=2 (200% max):
- baseline: 39-40K eps - 186%-190% CPU Usage.
- klauspost: 43-44.5K eps - 159% CPU usage. - `+10-11%` throughput. - `-15%` CPU usage.
Microbenchmarks also point show decreased ns/op on my machine, although it's not a perfect benchmark, since it's not entirely idle, but there's improvements, even for benchmarks with a higher p.
```
$ benchstat main.txt klauspost.txt …
```
=> Replace `compress/gzip` with `klauspost/compress`

appender.go, bulk_indexer.go
BulkIndexerConfig client was not public and therefore not configurable. Fix it.
=> Fix BulkIndexerConfig client is not public

appender.go, appender_test.go, bulk_indexer.go, config.go
Make document level retry status configurable with a default of 429 only.
=> Add RetryOnDocumentStatus config

bulk_indexer.go
See comments.
Directly passing a reusable bytes.Buffer is unsafe because of potential race condition on error scenarios introduced by the underlying RoundTripper implementation.
See:
https://pkg.go.dev/net/http#RoundTripper
> 	// RoundTrip must always close the body, including on errors,
// but depending on the implementation may do so in a separate
// goroutine even after RoundTrip returns. **This means that
// callers wanting to reuse the body for subsequent requests
// must arrange to wait for the Close call before doing so.**
We don't need a full copy of the buffer underlying slice since the sending goroutine is only reading from the buffer. We just need to make sure that `bytes.Buffer` other member variables aren't accessed and modified concurrently by different goroutines.
The call …
=> Don't pass a reused bytes.Buffer to the ES client

appender.go, bulk_indexer.go, bulk_indexer_test.go
A document should either be retried or failed in a request.
=> Fix retried docs to not be in FailedDocs

appender_test.go
Fixes the flaky `TestAppenderFlushMetric` test by increasing the number of events sent to they will always span two bulk requests in size.
Tested using:
```
$ go test -run=TestAppenderFlushMetric -count=100 -failfast ./...
?   	github.com/elastic/go-docappender/v2/docappendertest	[no test files]
ok  	github.com/elastic/go-docappender/v2	5.870s
$ go test -race -run=TestAppenderFlushMetric -count=100 -failfast ./...
?   	github.com/elastic/go-docappender/v2/docappendertest	[no test files]
ok  	github.com/elastic/go-docappender/v2	7.385s
```
=> test: fix flaky TestAppenderFlushMetric

appender.go, appender_test.go, bulk_indexer.go, config.go
Adds a new `RequireDataStream` option to the Appender, and BulkIndexer configurations. When set, it will send `?require_data_stream=true` in the `_bulk` request to Elasticsearch.
Closes #110
=> Support `require_data_stream` new config option

appender.go, appender_test.go, bulk_indexer.go
Updates the bulk_indexer to track all response status codes and report them appropriately as metrics. Also refactors tests to make them more succinct.
Closes #172
=> bulk_indexer: track all response status codes

appender.go, appender_test.go, config.go, go.mod
Add otel tracing support as a secondary tracing choice.
By default the current behaviour is retained: tracing with Elastic APM is preferred over otel tracing.
If Elastic APM tracing is not configured but otel tracing is, leverage otel tracing.
If no tracing is configured keep the current behaviour of skipping tracing.
Closes https://github.com/elastic/go-docappender/issues/45
=> add otel tracing support

.github/workflows/label-elastic-pull-requests.yml
No more finer-grained tokens but ephemeral tokens using a GH app
=> github-actions: use ephemeral tokens

appender.go, appender_test.go, bulk_indexer.go
This commit adds a new dimension to the `elasticsearch.events.retried` metric called `greatest_retry`. It represents the greatest observed retry count for a bulk request. This is useful to understand how many times documents in a bulk request have been retried.
=> `elasticsearch.events.retried`: Add retry dimension

appender.go, metric.go
This monotonic counter increments every time `Appender.Add`
detects that `bulkItems` channel length and capacity are
equal before sending the created BulkIndexerItem to the
channel.
As `bulkItems` is a buffered channel, monitoring length and
capacity allow us to detect possible blocking events when
sending to the channel due to exhausted capacity.
As `Appender.Add` could be called from multiple goroutines,
we are not guaranteed that every time this metric is
incremented the channel send will block, but should give us
a reasonably approximated picture.
=> add metric: docappender.blocked.add counter

bulk_indexer.go, bulk_indexer_test.go, docappendertest/docappendertest.go
Adds pipeline to the BulkIndexItem.  This will be necessary to implement https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37419
=> Add per event pipeline

bulk_indexer.go, bulk_indexer_test.go
When manipulating profiles data, we need to be able to use the `Update` action rather than `Create` all the time.
So this change allows passing custom actions rather than hardcoding create.
If no actions is provided, the default value will be `create`.
=> Allow passing a custom item action

appender_test.go
Closes https://github.com/elastic/go-docappender/issues/254
More description test naming. Also allows us to run individual tests:
```shell
go test -v -race ./... -run TestAppenderWithFailureStore
go test -v -race ./... -run TestAppenderRetryTooMany
```
Before this PR when running `go test -v -race ./... -run TestAppender`, most unit tests will run with the substring `TestAppender`
=> update test formating

bulk_indexer.go, bulk_indexer_test.go, docappendertest/docappendertest.go
This allow to collect telemetry for the size and count of documents sent to Elasticsearch.
=> Add telemetry headers for bulk requests
